import Header from "./Header1";
const News = () => {
    const News = [
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1002,
            date: "12/03/2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1003,
            date: "11/03/2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1004,
            date: "13/03/2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },
        {
            id: 1001,
            date: "13/03.2024",
            heading: "Ipl schedule announced",
            cover: " ",
            content: "IPL Media AdvisoryFebruary 22, 2024Schedule for first two weeks of TATA IPL 2024 announcedThe Board of Control for Cricket in India announced the schedule for the first two weeks of the TATA Indian Premier League (IPL) 2024, commencing from March 22, 2024, to April 7, 2024. During the two-week period, 21 matches will be played across 10 cities, with each team playing a minimum of three matches and a maximum of five.The 17th season will kick off with defending champions and five-time winners Chennai Super Kings taking on Royal Challengers Bangalore in Chennai on Friday. The first weekend will feature two double headers, beginning with the Punjab Kings hosting the Delhi Capitals on Saturday afternoon, followed by the Kolkata Knight Riders hosting the Sunrisers Hyderabad in the evening. On Sunday afternoon (March 24th), the action will shift to Jaipur, where the home team Rajasthan Royals will face the Lucknow Super Giants. Sunday evening will witness the home team Gujarat Titans, the 2022 champions and finalists of the last season going head-to-head with five-time winners Mumbai Indians.Having chosen to play their first two home matches in Visakhapatnam, the Delhi Capitals will first host the Chennai Super Kings on Sunday, 31st March in the port city and will then face the Kolkata Knight Riders at the same venue on Wednesday, 3rd April.As in the past, the BCCI will work closely with government and security agencies, following all necessary protocols and advisories related to the upcoming Lok Sabha Elections in India. Once the dates for the 18th Lok Sabha elections are announced, the Board will review and address any issues pertaining to the schedule of the first two weeks. Subsequently, the BCCI will work in tandem with local authorities to finalize the schedule for the remainder of the season, taking into account the polling dates.The detailed fixtures of the first two weeks can be accessed by clicking HERE. JAY SHAHHonorary SecretaryBCCI"

        },

    ]




    return (
        <Header name="LATEST NEWS" />
    )
}
export default News;